# Generated by Django 3.1.4 on 2020-12-21 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0020_auto_20201121_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactionMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('reaction', models.CharField(max_length=200)),
                ('guild_id', models.IntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='amongusgame',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='amongusgame',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='amongusgame',
            name='guild',
        ),
        migrations.DeleteModel(
            name='BotPermission',
        ),
        migrations.RemoveField(
            model_name='member',
            name='server',
        ),
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.DeleteModel(
            name='NotifierSub',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='server',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='playlistposition',
            name='queue',
        ),
        migrations.RemoveField(
            model_name='playlistposition',
            name='source',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reported_by',
        ),
        migrations.RemoveField(
            model_name='report',
            name='server',
        ),
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
        migrations.RemoveField(
            model_name='server',
            name='members',
        ),
        migrations.RemoveField(
            model_name='server',
            name='playlist',
        ),
        migrations.DeleteModel(
            name='VierGewinntGame',
        ),
        migrations.DeleteModel(
            name='AmongUsGame',
        ),
        migrations.DeleteModel(
            name='AudioSource',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
        migrations.DeleteModel(
            name='PlaylistPosition',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='Server',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
