# Generated by Django 3.1.4 on 2020-12-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reaction_mapper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(default='Alec is awesome', max_length=200),
            preserve_default=False,
        ),
    ]
