# Generated by Django 3.1.4 on 2020-12-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reaction_mapper', '0002_question_correct_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactionMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('reaction', models.CharField(max_length=200)),
                ('guild_id', models.IntegerField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
