# Generated by Django 3.1.4 on 2020-12-21 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reaction_mapper', '0003_auto_20201221_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reactionmapping',
            name='pub_date',
        ),
    ]
